# Generated by Django 3.2.5 on 2021-07-21 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0006_alter_assets_modality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('AP', 'Aplicação'), ('RE', 'Resgate')], default='AP', max_length=2, verbose_name='Tipo')),
                ('date', models.DateTimeField(verbose_name='Data de transação')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('unit_price', models.FloatField(verbose_name='Preço unitário')),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.assets', verbose_name='Ativo')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_transaction', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
