# Generated by Django 3.2.5 on 2021-07-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transactions_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('application', 'Aplicação'), ('rescue', 'Resgate')], default='application', max_length=25, verbose_name='Tipo'),
        ),
    ]
