# Generated by Django 3.2.5 on 2021-07-22 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transactions_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='unit_price',
            new_name='_unit_price',
        ),
    ]
