# Generated by Django 3.2.5 on 2021-07-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_rename_unit_price_transactions__unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='_unit_price',
            field=models.FloatField(db_column='unit_price', editable=False, null=True, verbose_name='Preço unitário'),
        ),
    ]
