# Generated by Django 3.2.5 on 2021-07-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Saldo'),
        ),
    ]
