# Generated by Django 3.2.5 on 2021-07-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='type',
            field=models.CharField(choices=[('CR', 'Cripto'), ('RV', 'Renda variavel'), ('RF', 'Renda fixa')], default='RF', max_length=2),
        ),
    ]
