# Generated by Django 3.2.5 on 2021-07-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_assets_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='type',
        ),
        migrations.AlterField(
            model_name='assets',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='modality',
            field=models.CharField(choices=[('CR', 'Cripto'), ('RV', 'Renda variavel'), ('RF', 'Renda fixa')], default='RF', max_length=2, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='value',
            field=models.FloatField(verbose_name='Valor'),
        ),
    ]
