# Generated by Django 3.2.5 on 2021-07-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20210720_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='modality',
            field=models.CharField(choices=[('Cripto', 'Cripto'), ('Renda variavel', 'Variable'), ('Renda fixa', 'Fixed')], default='Renda fixa', max_length=14, verbose_name='Modalidade'),
        ),
    ]
