# Generated by Django 3.2.5 on 2021-07-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_assets_modality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='modality',
            field=models.CharField(choices=[('Cripto', 'Cripto'), ('Renda variavel', 'Renda variavel'), ('Renda fixa', 'Renda fixa')], default='Renda fixa', max_length=14, verbose_name='Modalidade'),
        ),
    ]
